version: "3.7"
services:
  postgres:
    image: ankane/pgvector
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      postgres
      -c shared_buffers=1GB
      -c maintenance_work_mem=256MB
      -c max_parallel_maintenance_workers=4
