// app/seo.ts
import { initSeo } from "remix-seo";
import { siteMetadata } from "./utils/siteMetadata";
export const { getSeo, getSeoMeta, getSeoLinks } = initSeo({
  // Pass any SEO defaults for your site here.
  // If individual routes do not provide their own meta and link tags,
  // the tags generated by the defaults will be used.
  title: siteMetadata.title,
  titleTemplate: siteMetadata.title + " - %s",
  description: siteMetadata.description,
  openGraph: {
    url: siteMetadata.siteUrl,
    type: "website",
    siteName: siteMetadata.title,
    description: siteMetadata.description,
    title: siteMetadata.title,
    // images: [{ url: "", alt: "" }],
  },
  twitter: {
    title: siteMetadata.title,
    card: "summary_large_image",
    site: siteMetadata.siteUrl,
    description: siteMetadata.description,
    //  image: { url: "", alt: "" }
  },
});
