-- CreateTable
CREATE TABLE "AnonymousUser" (
    "id" TEXT NOT NULL,
    "sessionId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "ip" TEXT,
    "city" TEXT,
    "region" TEXT,
    "region_code" TEXT,
    "country" TEXT,
    "country_code" TEXT,
    "country_code_iso3" TEXT,
    "country_name" TEXT,
    "country_capital" TEXT,
    "country_tld" TEXT,
    "country_area" DOUBLE PRECISION,
    "country_population" DOUBLE PRECISION,
    "continent_code" TEXT,
    "in_eu" BOOLEAN,
    "postal" TEXT,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "latlong" TEXT,
    "timezone" TEXT,
    "utc_offset" TEXT,
    "country_calling_code" TEXT,
    "currency" TEXT,
    "currency_name" TEXT,
    "languages" TEXT,
    "asn" TEXT,
    "org" TEXT,
    "hostname" TEXT,
    "ua" TEXT,
    "browser_name" TEXT,
    "browser_version" TEXT,
    "browser_major" TEXT,
    "cpu_architecture" TEXT,
    "device_type" TEXT,
    "device_vendor" TEXT,
    "device_model" TEXT,
    "engine_name" TEXT,
    "engine_version" TEXT,
    "os_name" TEXT,
    "os_version" TEXT,

    CONSTRAINT "AnonymousUser_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AnonymousUser_sessionId_key" ON "AnonymousUser"("sessionId");
